### ISSUE TITLE
On MacOS UI is not updated when window goes Fullscreen

### ISSUE THREAD

**Issue by 0xIonRod** [Zireael07/Space-Frontier#3]
Hi!
I've launched the game in Window mode and it looks like that.

![image](https://user-images.githubusercontent.com/101790821/170852653-29c14cb7-772e-45c4-908e-d6a232022033.png)

Then I changed to fullscreen and got that

![image](https://user-images.githubusercontent.com/101790821/170852669-1353a333-9003-4072-99b1-da614906f590.png)

**Comment by 0xIonRod** [comment]
Godot 3.5-rc2
MacOs 12.3.1

**Comment by Zireael07** [comment]
Whoops, you're right, and this is not limited to MacOS.

This is likely me not using anchors correctly (or at all). Thanks for bringing this to my attention. The design resolution is pretty much my screen resolution so I never noticed :P

**Comment by Zireael07** [comment]
Should be fixed with https://github.com/Zireael07/Space-Frontier/commit/62d64d992b400d941e77251b2fd07a84807f8e0d

(Fixing the static UI elements wasn't that difficult. The biggest problem was with dynamically placed ones, i.e. planet labels and AI order overlays)
