### ISSUE TITLE
No LICENCE

### ISSUE THREAD

**Issue by 0xIonRod** [Zireael07/Space-Frontier#4]
Hi!

I was not able to find a LICENCE to the code. 

I'm working on an opensource industrial grade space sim called @LunCoSim.
Probably we could reuse some of your code if it's under MIT-like licence.

**Comment by Zireael07** [comment]
Thanks, this was just a personal project (you're pretty much the first person interested in it) so I never bothered to pick a license.

I did pick MIT, as was the case with my other project.

Closed in https://github.com/Zireael07/Space-Frontier/commit/90f4a2a86cc53e422550c1cd276b0a398cc9d592

PS. This is a 2D game and yours is a 3D project, so I'm not sure how much of the code is actually portable, apart from generic stuff like calculating habitable zones and the like.
